package cs.ut.util

const val MAINLAYOUT = "mainLayout"
const val NAVBAR = "navbar"
const val DEST = "dest"
const val JOBS_KEY = "client_jobs_key"
const val NEXT_ACTIVITY = "next"
const val OWNER = "job_owner"

const val COMP_ID = "compId"
const val CASE_ID_COL = "case_id_col"
const val ACTIVITY_COL = "activity_col"
const val RESOURCE_COL = "resource_col"
const val TIMESTAMP_COL = "timestamp_col"
const val LABEL_NUM_COLS = "label_num_cols"
const val LABEL_CAT_COLS = "label_cat_cols"

const val STATIC = "static"
const val DYNAMIC = "dynamic"
const val NUM_COL = "_num_cols"
const val CAT_COLS = "_cat_cols"

const val REMTIME = "remtime"
const val OUTCOME = "outcome"

const val PROPERTY = "property"
const val TRACKER_EAST = "trackerEast"

const val PAGE_LANDING = "landing"
const val PAGE_UPLOAD = "upload"
const val PAGE_LOGOVERVIEW = "logOverview"
const val PAGE_TRAINING = "training"
const val PAGE_VALIDATION = "validation"

const val LAST_STATE = "last_state"
const val PREFIX = "prefix_lenght_based"
const val FREQUENCY = "frequency"
const val COMBINED = "combined"
const val INDEX = "index_based"
const val ZERO = "zero"
const val STATE = "state_based"
const val CLUSTERING = "clustering"
const val RANDOM_FOREST = "random_forest"
const val GRADIENT_BOOST = "gradient_boosting"
const val DEC_TREE = "decision_tree"
const val XGBOOST = "xgboost"